version: '3'
services:
  webdacswalter2:
    container_name: webdacswalter2
    image: walterdacs2022:latest
    depends_on:
      - "db2"
    ports:
      - "8082:8081"
    links:
      - db2
    environment:
      DB_HOST: 'dbwalter2:3306'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'dacs2022'
      SPRING_PROFILES_ACTIVE: 'prod'
  db2:
    container_name: dbwalter2
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dacs2022'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
#    ports:
#        - '3306:3306'
#    expose:
#        - '3306'


